### ISSUE TITLE
Error in demo page

### ISSUE THREAD

**Issue by hare1039** [pinkie860219/WebMusicPlayerReact#1]
The "hare1039コレション" playlist will not iterate over the whole list.

**Comment by pinkie860219** [comment]
It's because the song "10. リアルワールド.mp3" had been added to list twice.
You can uncheck the checkbox to remove the song from list. This will remove all the same song from list. You then add the song back, problem will be solved.


The mind behind using checkbox to add song is to avoid add a song to the same list multi times. This may be caused by you click on the checkbox before fetching finished.

I think I'll add a loading icon to the dropdown before it finish fetching.
